[ 2017-10-30 14:42:19 ]: Traceback (most recent call last):
  File "/Users/wukui/PycharmProjects/untitled/test.py", line 43, in <module>
    num = a.return_num()
TypeError: unbound method return_num() must be called with test_class instance as first argument (got nothing instead)

[ 2017-10-30 14:43:17 ]: Traceback (most recent call last):
  File "/Users/wukui/PycharmProjects/untitled/test.py", line 41, in <module>
    a.a = 10
NameError: name 'a' is not defined

[ 2017-10-30 14:44:22 ]: Traceback (most recent call last):
  File "/Users/wukui/PycharmProjects/untitled/test.py", line 39, in <module>
    a.a = 10
NameError: name 'a' is not defined

